server:
  port: 0

spring:
  application:
    name: customer-service
  mvc:
    log-request-details: true
  cloud:
    consul:
      host: ${consul.host:localhost}
      port: ${consul.port:8500}
    loadbalancer:
      ribbon:
        enabled: false
  flyway:
    url: jdbc:postgresql://${postgres.host:localhost}:5432/${postgres.db:test}?currentSchema=customer
    user: ${postgres.user:kmandalas}
    password: ${postgres.password:passepartout}
#    schemas: demo
#    locations: db/migration
  r2dbc:
    url: r2dbc:postgresql://${postgres.host:localhost}:5432/${postgres.db:test}?currentSchema=customer
    username: ${postgres.user:kmandalas}
    password: ${postgres.password:passepartout}
  zipkin:
    base-url: http://${jaeger.host:localhost}:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    gr.kmandalas: DEBUG
    org.springframework.web: TRACE
    org.springframework.data.r2dbc: TRACE