server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: ${consul.host:localhost}
      port: ${consul.port:8500}
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: otp-service
          uri: lb://otp-service
          predicates:
            - Path=/otp-service/**
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ["*"]
            allowedMethods: ["POST","GET","DELETE","PUT"]
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"